language: csharp
mono: none
dist: bionic
dotnet: 3.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - WORKING_DIR=content

install:
  - cd $WORKING_DIR
  - dotnet restore
  - nvm install 10.0.0
  - nvm use 10.0.0

script:
  - npm install
  - dotnet build
