language: csharp
mono: none
dist: bionic
dotnet: 5.0

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - WORKING_DIR=content

install:
  - cd $WORKING_DIR
  - dotnet restore
  - nvm install 14.15.5
  - nvm use 14.15.5

script:
  - npm install
  - dotnet build
