language: csharp
mono: none
dotnet: 2.1.300

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
    - WORKING_DIR=content
  
install:
 - cd $WORKING_DIR
 - dotnet restore

script:
 - npm install
 - dotnet build