resources:
  - repo: self

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - master

variables:
  buildConfiguration: 'Release'

stages:
  - stage: build
    displayName: Build
    variables:
      - group: 'Global'
    jobs:
      - job: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
            displayName: 'Get Project Version as variables from Etch.OrchardCore.ThemeBoilerplate.csproj'
            inputs:
              path: Etch.OrchardCore.ThemeBoilerplate.csproj

          - task: CmdLine@2
            displayName: 'Compile front-end assets'
            inputs:
              script: 'npm run build'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              arguments: '-c $(BuildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              arguments: '-c $(BuildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack'
            inputs:
              command: pack
              versioningScheme: byEnvVar
              versionEnvVar: 'VERSION_MAJORMINORPATCH'

          - task: PublishPipelineArtifact@0
            displayName: 'Publish Pipeline Artifact'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'

  - stage: publish
    displayName: NuGet Publish
    dependsOn: build
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/tags/'))
    jobs:
      - job: Publish
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              source: 'current'
              path: '$(Pipeline.Workspace)'
          - task: NuGetCommand@2
            displayName: 'NuGet push'
            inputs:
              command: push
              packagesToPush: '$(Pipeline.Workspace)/**/drop/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'NuGet'
